spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms?characterEncoding=utf8&useSSL=false
    username: root
    password: hsp
# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
#      id-type: assign_id
      #配置类型别名所对应的包
      # 删除状态的值为：1 配置TableLogic 逻辑删除
      logic-delete-value: 1
      # 未删除状态的值为：0
      logic-not-delete-value: 0
  type-aliases-package: com.ztyedu.mybatisplus.pojo
  # 配置扫描通用枚举
#  type-enums-package: com.atguigu.mybatisplus.enums

